### ISSUE TITLE
mapchete convert write single GTIFF in parallel per block

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#260]
This function takes forever for larger datasets (I haven't found any other rasterio write as is so I assume it is handling most/all writing operations):
* https://github.com/ungarj/mapchete/blob/master/mapchete/io/raster.py#L449-L456

Probly can be properly setup here as it calls native mapchete functions:
* https://github.com/ungarj/mapchete/blob/master/mapchete/formats/default/gtiff.py#L397
* https://github.com/ungarj/mapchete/blob/master/mapchete/formats/default/gtiff.py#L555-L592

**Comment by ungarj** [comment]
> This function takes forever for larger datasets (I haven't found any other rasterio write as is so I assume it is handling most/all writing operations):
> 
> * https://github.com/ungarj/mapchete/blob/master/mapchete/io/raster.py#L449-L456

This function is only used when writing GTiff tiles for a TileDirectory.

> 
> Probly can be properly setup here as it calls native mapchete functions:
> 
> * https://github.com/ungarj/mapchete/blob/master/mapchete/formats/default/gtiff.py#L397
> * https://github.com/ungarj/mapchete/blob/master/mapchete/formats/default/gtiff.py#L555-L592

The lines above do the actual writing. File write operations in general (such as writing to single GTiffs like here) have to be handled by a single process as far as I know. Otherwise they could potentially overwrite each other and corrupt the file. In our case here this means that the process writing the file (which is the parent process) is the bottleneck, i.e. if the tile processes are faster than the parent process writing, it will be slower than writing a TileDirectory where the child processes write the tiles.

I'm afraid there is nothing we can do about this.
