### ISSUE TITLE
mapchete convert when writing to s3 seems to finish the upload but won't close the process

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#261]
* just stays at the full file size at the end and the process won't close/die
* maybe it's trying to do overviews/validation, etc.
* cog/overviews creations seems to be connected to this issue as well so it might be overviews rather then s3 upload

* recommendation, write all locally and upload with boto3 extra (don't know exactly how it's implemented now)

**Comment by Scartography** [comment]
* Update: with larger GTiffs even when empty, overviews take forever to generate, in comparison with gdaladdo where they run as expected

**Comment by ungarj** [comment]
> * just stays at the full file size at the end and the process won't close/die

You mean the process hangs forever? Please mind that with large GTiffs the upload takes a while. Have you verified it was successfully written to S3? (i.e. by reading it)

> * maybe it's trying to do overviews/validation, etc.

We are using the rasterio bindings here to generate the overviews, this usually takes a while as well. It seems odd though that this takes significantly longer than `gdaladdo` because rasterio should use the same internal GDAL bindings.

> * cog/overviews creations seems to be connected to this issue as well so it might be overviews rather then s3 upload
> * recommendation, write all locally and upload with boto3 extra (don't know exactly how it's implemented now)

Unless the output raster exceeds the [IN_MEMORY_THRESHOLD](https://github.com/ungarj/mapchete/blob/master/mapchete/formats/default/gtiff.py#L77) (which also works as an environment variable, so you can change it to your liking) it is created in memory, otherwise it is handled as you suggested by writing a temporary file and uploaded via boto3.

Thinking about it I suppose it could also potentially be that boto3 runs into timeouts when uploading the data to S3. So if one of the requests uploading the data runs into a timeout and this is not handled, the process will hang forever.

**Comment by ungarj** [comment]
boto3 seems to automatically split up large files into smaller chunks when uploading: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-uploading-files.html

**Comment by ungarj** [comment]
I guess we can try to set timeouts and maybe retry settings [here](https://github.com/ungarj/mapchete/blob/master/mapchete/io/_misc.py#L172) using a [configuration object](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html).

**Comment by Scartography** [comment]
duplicate of #260, COG overviews take forever in master process
