### ISSUE TITLE
write mapchete config to metadata.json

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#266]
* to check on attributes how the output was generated, should .mapchete files be lost
* useful for reproducing data as we usually put the specific params directly in the mapchete file

**Comment by Scartography** [comment]
just add a key {{xx:xx}, {machete_config: {input: ****, ...}}}, you can also put it as geojson in the output folder with process bounds  and properties == mapchete_config with name mapchete_config.geojson

**Comment by ungarj** [comment]
losing mapchete fies brings bad luck. old transsilvanian saying :)

i won't put this into metadata.json because it should only describe how the data is structured. as we will move into the stac tiled assets direction sooner or later maybe we find a way to append optional metadata there.

also, there is the issue on how to store different configurations which write into the same output like we do in sentinel-2 cloudless. we would have to store all of the bounds used for processing and more crucially keep it updated. say, if we processed a single tile afterwards with a slightly different config, we would have to add a new config and update the existing one. not that it is impossible but to me it sounds a bit too complicated. why not simply put the mapchete file(s) as they are in the root of the tile directory?

let's keep this in the backs of our heads though.

**Comment by Scartography** [comment]
> put the mapchete file(s) as they are in the root of the tile directory
yep sure, this will work

**Comment by ungarj** [comment]
closing for now
