### ISSUE TITLE
use "spawn" as default multiprocessing method

### ISSUE THREAD

**Issue by ungarj** [ungarj/mapchete#351]
it seems `fsspec` has issues when used with multiprocessing fork: https://github.com/dask/gcsfs/issues/379

**Comment by Scartography** [comment]
* even after the https://github.com/ungarj/mapchete/blob/dask/mapchete/_executor.py#L158 update it does not seem to work properly for `mapchete convert`
* when I change the code to `method=MULTIPROCESSING_DEFAULT_START_METHOD` for the method and hard-code it in it takes the `spawn` method for `convert` command otherwise it keeps switching to the `fork` method
* therefore some kwarg `multiprocessing_start_method` is being passed from somewhere (convert, execute) above

**Comment by Scartography** [comment]
Suggested solution from me

* make this line in `_execute.py` https://github.com/ungarj/mapchete/blob/dask/mapchete/commands/_execute.py#L30
* to `multiprocessing_start_method: str = MULTIPROCESSING_DEFAULT_START_METHOD,`
* do this for all the other commands just i case and pass the `multiprocessing_start_method` kwarg ideally down from each of the `commands` (execute, cp, convert, rm, etc.)

**Comment by ungarj** [comment]
I think I fixed it now. And learned in the process that a `dict.get('foo', 'bar')` does not set `bar` if `foo` was available in the dict but set to `None`. In that case the result is `None` which defaulted in this case to `fork`, not `spawn`...
